name: Cypress Tests

on: 
  pull-request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: pnpm/action-setup@v2
        with:
    version: 6.32.9
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          cache: 'pnpm'
          build: npm run build
          start: npm start
      